name: tests
on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DavidAnson/markdownlint-cli2-action@v1
        with:
          globs: "**/*.md"
